"""Build the deterministic Three.js point cloud from the approved Onyx plate.

The source PNG is a design reference used only at build time.  The runtime
renderer consumes packed geometry and colour attributes; it never draws the
plate as an image or texture.
"""

from __future__ import annotations

import base64
import hashlib
import math
import struct
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "qml" / "assets" / "onyx-humanoid-cyryx-v11.png"
TARGET = ROOT / "qml" / "web" / "data" / "onyx-humanoid-pointcloud-v1.js"
MIN_LUMINANCE = 8
SAMPLE_FACTOR = 0.80


def _sample_hash(x: int, y: int) -> float:
    value = ((x * 73_856_093) ^ (y * 19_349_663) ^ 0x9E3779B9) & 0xFFFFFFFF
    return value / 4_294_967_296


def _build_payload() -> tuple[bytes, int, int]:
    image = Image.open(SOURCE).convert("RGBA")
    width, height = image.size
    pixels = image.load()
    payload = bytearray()

    for y in range(height):
        for x in range(width):
            red, green, blue, _alpha = pixels[x, y]
            luminance = max(red, green, blue)
            if luminance < MIN_LUMINANCE:
                continue
            probability = min(1.0, math.pow(luminance / 255.0, 0.72) * SAMPLE_FACTOR)
            if _sample_hash(x, y) >= probability:
                continue
            payload.extend(struct.pack("<HHBBBB", x, y, red, green, blue, luminance))

    return bytes(payload), width, height


def main() -> None:
    payload, width, height = _build_payload()
    encoded = base64.b64encode(payload).decode("ascii")
    wrapped = "\n".join(f"  '{encoded[index:index + 100]}'," for index in range(0, len(encoded), 100))
    source_sha = hashlib.sha256(SOURCE.read_bytes()).hexdigest()
    point_count = len(payload) // 8
    output = f"""// Generated by scripts/generate_humanoid_pointcloud_v1.py.
// Source SHA-256: {source_sha}
export const ONYX_POINT_COUNT = {point_count};
export const ONYX_SOURCE_WIDTH = {width};
export const ONYX_SOURCE_HEIGHT = {height};
const CHUNKS = [
{wrapped}
];

export function decodeOnyxPointCloud() {{
  const binary = atob(CHUNKS.join(''));
  const bytes = new Uint8Array(binary.length);
  for (let index = 0; index < binary.length; index += 1) bytes[index] = binary.charCodeAt(index);
  return bytes;
}}
"""
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(output, encoding="utf-8", newline="\n")
    print(f"generated {TARGET.relative_to(ROOT)} with {point_count} points")


if __name__ == "__main__":
    main()
